apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
    - image: twss/hello-world-nginx
      context: nginx
      custom:
        buildCommand: ../buildx.sh
